<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC7d4Tb4\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC7d4Tb4/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC7d4Tb4.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC7d4Tb4\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerC7d4Tb4\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'C7d4Tb4',
    'container.build_id' => '7c814d1b',
    'container.build_time' => 1638867859,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC7d4Tb4');
